import React, { useState } from "react";
import Popup from "../Popup/Popup.js"
import "./GenGameRules.css";
import GameBoard from "./GameBoard.js";


const ConvUnitRules = () => {
  const [ showBoard, setShowBoard ] = useState(false);
  return (
    <div className="general-rules-wrapper">
        <h1 className="text-center-bold">Deterrence General Game Rules</h1>
            <p className="indent padding-top">Welcome to Deterrence, a game where <em>CHESS ENTERS THE NUCLEAR AGE!</em>  Thank you for playing the game that will officially replace chess for all time and eternity going forward.  Your patience and dedication as one who wishes to learn Deterrence will offer YOU THE FOUNDING PLAYERS countless enjoyment as you battle it out with your opponents for strategic dominance.  Deterrence introduces three new concepts of gameplay, while using the existing chess gameplay.  These three new Game Concepts are described below.</p>
            <p className="indent padding-bottom">You will learn about the various Codes for everything as you read these Rules.  Each newly introduced concept will have its companion Score Sheet Code next to it in parenthesis.  Note that the parenthesis used throughout ARE NOT part of these Codes themselves.  Since Deterrence has both Fixed and Variable Rules with time limitations associated with them, see below for more information, a Score Sheet is used to record activities during the Complete Turns throughout EVERY GAME PLAYED of Deterrence.</p>
            <h2 className="text-center-bold">Three New Game Concepts:</h2>
            <h4 className="bold padding-top">FIRST NEW GAME CONCEPT:  <em>NUCLEAR AND SDI DEFENSE UNITS</em></h4>
            <p className="indent">The Use of nuclear weapons (the new Nuclear Units) and the new SDI Defense Units to protect other Units from nuclear destruction.</p>
            <h4 className="bold">SECOND NEW GAME CONCEPT: <em>YOUR NEW TREATY NEGOTIATIONS CHART</em></h4>
            <p className="indent">The Use of a Treaty Negotiations Chart to change one, some, or all of the new Variable Rules and one, some, or all of the new Points Settings.  Each Player has ONE OVERALL OPPORTUNITY to ask the other Player for a Treaty negotiating session to "make each game their own."  This ensures that Deterrence becomes a constantly-changing and ever-evolving "platform" that will be more difficult for artificial intelligence (AI) platforms to always supply human players with the strongest move in any game.  The future World Human Deterrence Champion, unlike the current World Human Chess Champion, can rest assured that AI will not supplant humanity from premier playing status anytime soon.  The human Players will also know that humanity has a distinct advantage in overall negotiating ability compared with AI (at least for now).  This allows human Players to both customize each game they play while also enjoying each game played more thoroughly. Also, the psychological aspect of negotiating in general offers further excitement when playing Deterrence that chess does not have.</p>
            <h4 className="bold">THIRD NEW GAME CONCEPT: <em>PLAYING FOR POINTS ALONG WITH POSITION</em></h4>
            <p className="indent padding-bottom">Following from #2 above, in Deterrence, the Players compete for TWO TOTAL Outcome Points, one for the POSITIONAL PORTION of the game, similar to chess's ONE OVERALL Outcome Point per game, and then the SECOND OUTCOME POINT for the new POINTS PORTION of the game.  This second Outcome Point is also awarded when the first Outcome Point is awarded, when the game ends in much the same way (with some new wrinkles) as a game of chess ends.</p>
        <h2 className="text-center-bold">Setting Up the Game Board:</h2>
            <p className="indent padding-top">Anybody can play Deterrence using a 64-square playing surface with alternating colors, one complete chess piece set, and one complete checkers set.  Future versions of Deterrence will have direct playability on this website using a "virtual" Game "Board," much like today's popular chess applications.  Playing "against the computer" in Deterrence, however, might take awhile, as many new and exciting, challenging and rewarding aspects of gameplay have been added.  The setup for the start of the game is identical in layout to how a game of chess starts.  There is new terminology introduced within Deterrence which will respect the identities of players from different groups within humanity as well as new names for the Conventional Units, formerly the chess "pieces."  Deterrence does not rely on the "white" versus "black" concept used in chess, but rather the "Starting Player" versus the "Responding Player."  This new way of referring to each of the two Players in a game allows for future customizability in each Player selecting the color of each of their Units.  In Deterrence, the pawn in chess is known as the Infantry Unit.  The Knight is known as the Airdrop Unit.  The Bishop is known as the Sergeant Unit.  The Rook is known as the Lieutenant Unit.  The Queen becomes the General Unit, and lastly, the King becomes the President Unit.  Note the gender-neutral Unit names, replacing chess's dated patriarchal "piece" names.  Also, in Deterrence, the player using the "black" or "darker-colored" pieces in a chess set to symbolize the newly renamed Conventional Units CAN BE the Starting Player!  All that is necessary is making sure that the h1 square on a chess or checkers board is in fact the "black" or "darker-colored" square.  Then the opposing Player with the "white" or "lighter-colored" chess pieces used to symbolize the new Units would be the Responding Player.  In today's ever-evolving cultural and social landscape, the best way to ensure inclusivity for traditionally marginalized groups of people is to ALLOW ALL of them to play Deterrence in the same way and from the same "point-of-view."  In the future, Players can "play" as the Treaty Organization, country, state, school, political party, or other such "roles" as they wish, even being able to customize the names of their individual Units.  The possibilities are endless!</p>
            <p className="indent padding-bottom">To set up a game of Deterrence, do exactly the same things as you would for a chess game.  Just as in chess, the horizontal rows of squares are called RANKS, while the vertical columns of squares are called FILES.  Each rank is numbered 1 through 8, starting from the starting Player's rank closest to that Player.  Just as in chess, the files are labelled from the letter (a) through the letter (h), starting from the Starting Player's left-hand side.  Click the button to see the board with traditional "lighter-coloring" on the h1 square!</p>
            <span className="board-btn-wrapper">
              <button id="ShowBoardCode" className="board-codes-btn" onClick={() => setShowBoard(true)}>See your Game Board!</button>
              <Popup trigger={ showBoard } setTrigger={ setShowBoard }>
                <GameBoard />
              </Popup>
          </span>
            <p className="indent padding-top">In addition to your brand-new Conventional Units, in Deterrence, three new types of Nuclear Units join the fray, along with the new SDI Defense Units to protect designated Units from destruction in a Nuclear Unit firing.  These Units can be symbolized by whatever the Players wish, such as coins, poker chips, or other such "markers."  Traditionally, when the game first underwent testing, the Starting Player used 6 of the red checkers for the Nuclear Units, and 6 of the black checkers for the SDI Defense Units.  The opposite holds true for the Responding Player, who used the remaining 6 black checkers to denote Nuclear Units and the remaining 6 red checkers to denote the SDI Defense Units.  It is important to note that the game DOES NOT START OFF with any other Units besides each Player's 16 total Conventional Units.</p>
            <p className="indent">For the Starting Player, the 8 Infantry Units start off on squares a2, b2, c2, d2, e2, f2, g2, and h2, just as the Pawns in chess do.  For the Responding Player, those 8 Infantry Units start off on squares a7, b7, c7, d7, e7, f7, g7, and h7.</p>
            <p className="indent">For the Starting Player, the 2 Lieutenant Units start off on squares a1 and h1.  For the two Responding Lieutenant Units, the squares they start on are squares a8 and h8.</p>
            <p className="indent">Moving inward, for the Starting Player, the two Airdrop Units start on squares b1 and g1, and then their Responding counterparts begin affairs on squares b8 and g8.</p>
            <p className="indent">Continuing on, the two Starting Sergeant Units rest on squares c1 and f1, and their Responding Sergeants get things going on squares c8 and f8.</p>
            <p className="indent">In the middle of the first rank, the Starting General rests on square d1, while the Responding adversary starts on square d8.  The Starting Player's President Unit starts on square e1, while the Responding Player's leader begins on square e8.</p>
            <p className="indent">For the Nuclear Units, each Player use one checker for the Tactical Nuclear Unit, star-side up for a Mobile Tactical Nuclear Unit (MTN), and crown-side up for the Fixed Tactical Nuclear Unit (FTN).  All types of Mobile Nuclear Units CAN BE MOVED, while their Fixed colleagues CANNOT MOVE.  In the present form of Deterrence, each Player may have ONE TOTAL Tactical Nuclear Unit, with type decided at Deploy (D) time.  The purpose of this Rule is to ensure less likelihood of a game immediately devolving into a nuclear exchange.  Both the tactics and the strategy of chess need to be preserved.  The future Deterrence Working Group might change this rule in future versions of Deterrence, based upon the will of the Players who subscribe to online services through this website.  See Official Rules: All Unit Codes: Nuclear Units, to find these specific Units and to learn more about them.</p>
            <p className="indent">For the new Intermediate Nuclear Unit, each Player uses two checkers each of the designated color "stacked" one upon the other, with the top checker showing a star for the Mobile Intermediate Nuclear Unit (MIN), and the crown showing on the top checker for the Fixed Intermediate Nuclear Unit (FIN).  In the present form of Deterrence, each Player may have ONE TOTAL Intermediate Nuclear Unit, with type decided at Deploy (D) time.  The purpose of this Rule, and other FIXED RULES for Nuclear Units, is to ensure less likelihood of a game immediately devolving into a nuclear exchange.  Both the tactics and the strategy of chess need to be preserved.  The future Deterrence Working Group might change this rule in future versions of Deterrence, based upon the will of the Players who subscribe to online services through this website.  See Official Rules: All Unit Codes: Nuclear Units, to find these specific Units and to learn more about them.</p>
            <p className="indent">Lastly, the biggest of the blower-uppers enters the room:  The Strategic Nuclear Unit (SN), which is always a Fixed model due to its unlimited range, with the stack of 3 checkers with the crown showing up on the topmost checker symbolizing this Unit.  In the present form of Deterrence, each Player may have ONE TOTAL Strategic Nuclear Unit, which is always Fixed at Deploy (D) time.  The purpose of this Rule, and other FIXED RULES (Rules THAT CANNOT EVER be changed during either one or both rounds of Treaty negotiations) for Nuclear Units, is to ensure less likelihood of a game immediately devolving into a nuclear exchange.  Both the tactics and the strategy of chess need to be preserved.  The future Deterrence Working Group might change this rule in future versions of Deterrence, based upon the will of the Players who subscribe to online services through this website.  See Official Rules: All Unit Codes: Nuclear Units, to find these specific Units and to learn more about them.</p>
            <p className="indent padding-bottom">Finally, who wants to lose a Unit and not get anything in return for it?  Well, to prevent the loss of selected Units in different ways, the SDI Defense Units can be "bought," if you will, with Points and placed on the Game Board.  Up to six (6) total SDI Defense Unit "buys" can be made throughout the course of an entire game, inclusive of both types.  The first type of SDI Defense Unit is the Mobile SDI Defense Unit (MSDI), and then of course the Fixed SDI Defense Unit (FSDI).  As is ths case above with the 3 types of Nuclear Units, the Mobile Units can move, while the Fixed ones CANNOT MOVE.  The Mobile SDI Defense Unit CAN ONLY PROTECT one other "paired" Unit at a time, but does not have to protect the one Unit.  Whereas the Fixed SDI Defense Unit PROTECTS ALL UNITS on that one square it rests on, from nuclear annilihation.</p>
        <h2 className="text-center-bold">When the Game Starts:</h2>
            <p className="indent padding-top padding-bottom">In the game of chess, "White" has 20 possible "moves" to make to get the game underway.  Sixteen possible "pawn" moves and four possible "Knight" moves.  In Deterrence, this STARTING PLAYER can make the same sixteen Infantry Unit (as in chess, no code) Complete Turns, four Airdrop Unit (A) Complete Turns, one of the available Declare Envoy (E=)Complete Turns (7 possibilities), the Begin Treaty Negotiations (BNEG) Complete Turn, and the eight possible squares to Deploy (D) a Tactical Nuclear Unit Complete Turn, for a new total of 36 possible Complete Turns!  Refer to Official Rules:  All Score Sheet Rules, and other locations throughout these Rules, to learn the differences between a Complete Turn (everything moving and changing on that Player's Turn) versus an Element within a Complete Turn (Can either be Order Elements, or Move Elements, see these sections of the Official Rules for more information and to learn about the dizzying array of possibilities here)!  It's like the black-and-white TV just DISAPPEARED and GOT REPLACED by a new 8K Ultra High-Definition color unit.  What an amazing difference!</p>
            <p></p>
            <p></p>
            <p></p>
        <h2 className="text-center-bold">When the Game Ends:</h2>
            <p className="indent padding-top">In chess, the Players know that either one Player WINS and the opposing Player DOES NOT, or the game ends in a draw (no winner).  Any one of the same events can happen in Deterrence, with the following possibilities for end-of-game results:</p>
            <p className="indent padding-bottom">Before getting to that, just as in chess, the overall goal of the game is to be the Player who <em>checkmates</em> the opposing President WHILE ALSO having scored more total game Points (Score Sheet Game Points added to the Cash Value Game Points) than the vanquished opposing Player.  Those who have regularly played in chess tournaments know that a chess game only offers one "point" in metaphorical terms describing the outcome of the game.</p>
            <h3 className="text-center-bold">The Six Ways to Distribute the Two Outcome Points:</h3>
            <h4 className="bold divider padding-top"><em>FIRST WAY:  </em>The Starting Player WINS THE GAME, and BOTH of the TWO POSSIBLE OUTCOME Points, which is a 2.0 - 0.0 result.</h4>
            <h4 className="bold divider"><em>SECOND WAY:  </em>The Starting Player WINS THE GAME, and ONE of the TWO POSSIBLE OUTCOME Points, while sharing, or HALVING, the OTHER one which is a 1.5 - 0.5 result.</h4>
            <h4 className="bold divider"><em>THIRD WAY:  </em>The game ends in a DRAW, with EACH PLAYER WINNING ONE of the TWO POSSIBLE OUTCOME Points, which is a 1.0 - 1.0 result.</h4>
            <h4 className="bold divider"><em>FOURTH WAY:  </em>The game ends in a DRAW, and BOTH of the TWO POSSIBLE OUTCOME Points ARE HALVED by EACH PLAYER, which is a 1.0 - 1.0 result.</h4>
            <h4 className="bold divider"><em>FIFTH WAY:  </em>The Responding Player WINS THE GAME, and ONE of the TWO POSSIBLE OUTCOME Points, while sharing, or HALVING, the OTHER one, which is a 0.5 - 1.5 result.</h4>
            <h4 className="bold divider"><em>SIXTH WAY:  </em>The Responding Player WINS THE GAME, and BOTH of the TWO POSSIBLE OUTCOME Points, which is a 0.0 - 2.0 result.</h4>
          
    </div>
  )
}

export default ConvUnitRules;