import React from "react";
import "./TreatyRules.css";

const TreatyRules = () => {
  return (
    <div className="treaty-rules-wrapper">
        <h2 className="text-center-bold padding-top padding-bottom">Deterrence Official Rules:  Treaty Negotiations Chart</h2>
        <hr className="padding-bottom" />
        <h3 className="text-center-bold">Do you want to Shake Things Up?</h3>
        <h4 className="padding-top padding-bottom">In chess, both Players know that all rules always remain the same throughout the course of the game.  Because of this, the computer software suites that have been developed are now powerful enough to supply any human Player with the strongest move(s) in any given game at any given time.  Even the World Human Champions cannot defeat the best "virtual" opponent(s).  Therefore, players cannot be entirely sure, that when playing online or in-person, for that matter, that they in fact are playing the opponent(s) they think they are playing.  Cheating can be difficult to both eradicate and prevent, even within the setting of "over-the-board" or "in-person" chess tournaments, due to both the availability and capability of today's mobile connectivity devices.</h4>
        <h3 className="text-center-bold">Introducing Your New Treaty Negotiations Chart</h3>
        <p className="padding-top padding-bottom">The Deterrence Treaty Negotiations Chart addresses this first concern of chess by allowing Players to play the game with a custom set of Variable Rules coupled with Points Settings each time, reflecting the way in which each Player prefers to play, and the results of the two total available rounds of Treaty Negotiations.  The Fixed Rules cannot be changed during the process of Treaty Negotiations (see Deterrence Official Rules:  Fixed Rules, for more information).  Each Player has only one opportunity to ask the opposing Player for Treaty negotiations throughout the course of each game. Either or both Players can elect to forego asking for a Treaty.  Treaty Negotiations can occur at any point during the game, up to and inclusive of the Complete Turn prior to the Complete Turn that ends the game, when the position has been decided (win-lose-draw).</p>
        <p className="padding-bottom">It is important to emphasize here that ALL FIXED RULES (meaning all Rules NOT included in the Treaty Negotiations Chart, are NOT CHANGEABLE at ANY TIME during the game.  All of the Rules included in the Treaty Negotiations Chart ARE INDEED Variable Rules, which of course can be changed during either one or both rounds of Treaty negotiations.  Also, ALL POINTS SETTINGS, the settings where both Players must "apply Points" under various circumstances, ARE INCLUDED in the Treaty Negotiations Chart, and are therefore changeable.  Also important to note is that most of the Points Settings can be any real mathematical number between -10.0 and +10.0, inclusive.  Any Points Settings selections entered into the online digital versions of Deterrence WILL ROUND OFF any decimal-place digits NOT COUNTING THE FIRST ONE entered TO THE RIGHT of the decimal point.  No matter how peculiar or unique these Points Settings entries are during either one or both rounds of Treaty negotiations is(are) EACH ONE MUST be a mathematically real number between and inclusive of -10.0(whatever got rounded off) through +10.0(whatever got rounded off).  In cases where real numbers BELOW 0.0 or 1 (integer-only settings) do NOT MAKE SENSE, limitations have been included to account for this (see Official Rules: All Score Sheet Rules, for more information).</p>
        <h3 className="text-center-bold">The Three Ways Treaty Negotiations Might Proceed:</h3>
        <p className="padding-top">The Player answering a request for Treaty Negotiations can respond in one of the following three ways: ( ONE )refuse a Treaty outright ( the Treaty is not agreed to, and the Default Settings within the Treaty Negotiations Chart the game begins with or the settings in the existing Treaty from the first round of negotiations remain in effect ), ( TWO ) can participate in a negotiating session that results in the failure of both Players to agree to make the same changes to the Treaty ( the Treaty is not agreed to, and the current settings the game has, as explained above, remain in effect ), or, in the last case ( THREE ), an agreement is successfully reached, whereby all Variable Rules changes and Points Settings changes have been completely agreed to by both Players exactly, the Treaty takes effect at that time on the subsequent Complete Turn, and that Treaty now changes those Variable Rules and/or Points Settings that the Players have agreed to change during negotiations.</p>
        <p>If the first round of negotiations results in an agreement, the Treaty taking effect is called the First Treaty. If the second round of negotiations also results in agreed-to changes after the First Treaty has been implemented, the second Treaty taking effect is called a Revised Treaty.  If the second round of negotiations DOES NOT end in an agreement, the First Treaty remains in effect, just as the Default Settings of the Treaty Negotiations Chart would have remained in effect had there not been a First Treaty agreed to in the first round of negotiations.  A second round of negotiations can also be used to return a First Treaty's selections back to the game's Default Settings in the Treaty Negotiations Chart.</p>
        <p>The other difficulty within the game of chess relates to the virtual certainty that a Player behind in material or behind in the positional layout will lose the game if the "leading" Player has a at least a minimal level of playing ability.  To address this concern, Deterrence has introduced the concept of Game Points.  The Treaty allows each player the opportunity to change Points Settings affecting the distribution of Score Sheet Game Points, depending on what occurs during the course of the game.  The Cash Value Game Points of each of the Conventional Units, and each Mobile Nuclear Unit, and each Mobile SDI Defense Unit cannot be changed during Treaty Negotiations.  These settings are in fact, Fixed Rules.</p>
        <h3 className="text-center-bold">The Deterrence Treaty Negotiations Chart Sections:</h3>
        <h3 className="padding-top padding-bottom section-color">Section One:  Settings Relating to Drawn Outcomes at the End of the Game:</h3>
            <h4 className="text-center padding-bottom">The first setting:  Consecutive Complete Turn Limit:</h4>
              <p>This setting affects when a drawn POSITION ONLY (1st of the two Outcome Points) can be automatically declared as a result of the CONSECUTIVE COMPLETE TURNS that BOTH PLAYERS COMPLETE WITHOUT either of the following conditions being true:  1.  All of the Move Elements DO NOT CONTAIN Infantry MOVEMENT of any kind (The Infantry Unit(s) can still remain on the Game Board.  2.  That NOT ONE of these Consecutive Complete Turns involves either the capturing (x) or destroying (z) of ANY ONE UNIT of ANY TYPE.</p>
              <p>If EVEN ONE of either of these two conditions IS NOT MET for ANY ONE of the Complete Turns consecutively occurring (usually at the endgame portion of play), the "count" must be restarted.</p>
              <p>In the event that the Consecutive Complete Turn Limit is reached, the POSITIONAL PORTION (1st of the two Outcome Points) OF THE GAME automatically ends in a draw (0.5 - 0.5), and the Players then total both each of their Score Sheet Game Points and Cash Value Game Points to determine the result of the POINTS PORTION (2nd of the two Outcome Points) OF THE GAME, to determine then the FINAL RESULT of the game (see Official Rules:  All Score Sheet Rules, for more information).</p>
              <p>United States Chess Federation (USCF) Tournament Players usually know that this Limit is 50 consecutive "moves" in total.  In Deterrence, this is also the Default Setting within the Treaty Negotiations Chart for this rule.  The Players may agree during either or both rounds of Treaty negotiations to CHANGE THIS SETTING to any POSITIVE INTEGER VALUE inclusive of 1 through 100.</p>
            <h4 className="padding-top padding-bottom text-center">The second setting:  Do Equal Amounts of Game Points Draw the Whole Game?</h4>
              <p className="padding-bottom">Unlike chess, which only involves play for one Outcome Point, Deterrence has TWO OUTCOME POINTS TOTAL that the Players compete for during each game.  What this setting allows the Players to do is to CHANGE THE VARIABLE RULE for the DETERMINATION OF THE FIRST OUTCOME POINT for the POSITIONAL PORTION of the game in the rare event that the POSITIONAL PORTION of the game has ended WITH BOTH PLAYERS EACH having AN EXACTLY MATHEMATICALLY EQUAL Game Points Total (both types of Game Points added together).</p>
              <p className="padding-bottom">If this Variable Rule is CHANGED TO YES, then in the event that both Players having an EXACTLY EQUAL TOTAL of Game Points at the conclusion of the position DOES OCCUR, the POSITIONAL PORTION OF THE GAME also is automatically DRAWN AS WELL, regardless of how the game just ended, and each Player therefore receives ONE-HALF of EACH OF THE TWO OUTCOME POINTS, resulting in a 1.0 - 1.0 DRAWN GAME.</p>
              <p className="padding-bottom">The Default Setting is:  NO, meaning that the POSITIONAL PORTION OF THE GAME remains independently determined from the POINTS PORTION of the game.</p>
            <h4 className="text-center padding-bottom">The third setting:  Do Drawn Positions Draw the Whole Game?</h4>
              <p className="padding-bottom">Unlike chess, which only involves play for one Outcome Point, Deterrence has TWO OUTCOME POINTS TOTAL that the Players compete for during each game.  What this setting allows the Players to do is to CHANGE THE VARIABLE RULE for the DETERMINATION OF THE SECOND OUTCOME POINT for the POINTS PORTION of the game in the event that the POSITIONAL PORTION of the game has ended IN A DRAWN OUTCOME.</p>
              <p className="padding-bottom">If this Variable Rule is CHANGED TO YES, then in the event that both Players have REACHED A DRAWN POSITION, the POINTS PORTION OF THE GAME also is automatically DRAWN AS WELL, regardless of how many TOTAL GAME POINTS each of the two Players has.  Therefore, each Player receives ONE_HALF of EACH OF THE TWO OUTCOME POINTS, resulting in a 1.0 - 1.0 DRAWN GAME.</p>
              <p className="padding-bottom">The Default Setting is:  NO, meaning that the POINTS PORTION OF THE GAME remains independently determined from the POSITIONAL PORTION of the game.</p>
            <h4 className="text-center padding-bottom">The fourth setting:  The "Repetition of Position" Setting:</h4>
              <p className="padding-bottom">This setting refers to the rule that USCF Tournament Players usually refer to as the "threefold-rep" Rule whereby a position in a game of chess (and therefore the whole game) can legally be automatically declared drawn WITHOUT the mutual agreement of both Players being necessary.  When both of the following conditions are met, the position can be declared drawn:  1.  When it is the SAME PLAYER'S "move," AND 2.  When EVERYTHING within the POSITION has occurred in EXACTLY THE SAME LAYOUT for inclusive of three "moves" total, even without the "moves" having consecutively occurred.  The game in a USCF chess tournament therefore can be declared drawn.</p>
              <p className="padding-bottom">Therefore, in a game of Deterrence, the Default Setting for this Rule is: THREE COMPLETE TURNS, and the Players may CHANGE THIS SETTING to ANY POSITIVE INTEGER between 1 and 10, inclusive of both numbers, within either or both rounds of Treaty negotiations.</p>
        <h3 className="padding-bottom padding-top section-color">Section Two:  Settings for Using All Nuclear and SDI Defense Units:</h3>
            <h4>The first setting:  Are the use of Nuclear Units and SDI Defense Units legal?</h4>
            <h4>The second setting:  Select the yield of Strategic Nuclear (SN) Units:</h4>
            <h4>The third section of settings:  All Nuclear/SDI Defense Points Settings:</h4>
            <h4>The fourth setting:  Complete Turn Wait for Activating (C) Nuclear Units:</h4>
        <h3 className="padding-top padding-bottom section-color">Section Three:  Settings for Arming (R) and Handing Off (HO) Elements:</h3>
            <h4 className="text-center padding-bottom">The first setting:  Legality of HAND OFF (HO) Move Elements:</h4>
              <p className="padding-bottom">This first setting allows the Players to agree to either make these Move Elements COMPLETELY ILLEGAL or LEGAL BASED ON THE BELOW SELECTIONS within this Section for all of the applicable types of UNITS BEING MOVED which CANNOT move on their own accord, meaning the Mobile SDI Defense Unit (MSDI), or the Mobile Tactical Nuclear Unit (MTN), or the Mobile Intermediate Nuclear Unit (MIN) or any "one-Unit" combination of these Units.  This first setting DOES NOT have anything to do with whether or not these Move Elements count as ONE COMPLETE TURN on the Score Sheet.</p>
              <p className="padding-bottom">The choices for this setting available to the Players during either round or both rounds of Treaty negotiations are ONLY ONE of the FOLLOWING FOUR choices:  1.  None of these Move Elements Allowed at All, 2.  Only Adjacent Hand Offs Allowed, 3. Only Distant Hand Offs allowed, and 4. Both Adjacent and Distant Hand Offs allowed.</p>
              <p className="padding-bottom">The Default Setting is:  YES, ADJACENT SQUARES ONLY, meaning that the sending friendly Conventional Unit must be on a square adjacent to the receiving friendly Conventional Unit, of course within the sending Unit's movement RANGE.  In the case of Mobile Nuclear Unit Hand Offs (can be Tactical or Intermediate) both Conventional Units must both also be of the same type (refers to which Units "pair" with which Nuclear Units (see Official Rules: All Unit Codes, to refer to based on which type of Units are involved and allowed in the Hand Off Move Element being made.))</p>
            <h4 className=" text-center padding-bottom">The second setting:  Applicable only to Infantry Unit (no code) Handing Off (HO):  </h4>
              <p className="padding-bottom">This setting is designed to allow the Players the choice of how Infantry Units may Hand Off Mobile SDI Defense Units or Mobile Tactical Nuclear Units.  The players are given three choices and may select ONLY ONE of these THREE CHOICES during either one or both rounds of Treaty negotiations.</p>
              <p className="padding-bottom">The selection options are:  1.  Forward only, 2.  Backward only, or 3. Both forward and backward.  The Default Setting for this is: FORWARD ONLY, meaning that Infantry Units may ONLY HAND OFF to one of the two squares at a time they are eligible to capture (x) or destroy (z) to, or in cases of more than one Infantry Unit on the same file, ONE FORWARD SQUARE ahead of the Unit making the Hand Off Move Element.  Keep in mind that since the Infantry Unit is ONLY ALLOWED to capture to one square both adjacently and diagonally forward to it, Handing Off at a distance in either direction is NOT ALLOWED (a Fixed Rule).  The Infantry Unit also MAY NOT EVER be allowed to HAND OFF horizontally (rank), since this is illegal out-of-range movement for Infantry Units, but MAY HAND OFF vertically to "doubled" or, in rare cases "tripled" Infantry Units (see above explanation for the forward only case) on the same file, dependent upon the direction(s) selected herein.</p>
            <h4 className="text-center padding-bottom">The third setting:  If allowed, when do these Elements count as One COMPLETE TURN?</h4>
              <p className="padding-bottom">This setting allows for Players to select ONE of the following FOUR CHOICES to determine when Hand Off (HO) Move Elements are to be the ONLY MOVE ELEMENT ALLOWED during the Complete Turn that they occur in.  A Complete Turn Hand Off requires that the Player then wait for the next Complete Turn to make a Move Element with either one of those two Conventional Units involved in the prior Hand Off Move Element.  The three options for this setting are:  1.  Only Adjacent Hand Offs are COMPLETE TURNS, 2.  Only Distant (if allowed above) Hand Offs, 3.  All Hand Offs count as ONE COMPLETE TURN, and 4. Neither type of Hand Off Move Element is a COMPLETE TURN.</p>
              <p className="padding-bottom">The Default Setting is:  #2, ONLY DISTANT HAND OFFS (IF ALLOWED ABOVE)</p>
            <h4 className="text-center padding-bottom">The fourth setting:  Arming a Nuclear Unit at a DISTANCE ONLY counts as ONE COMPLETE TURN?:</h4>
              <p className="padding-bottom">Here, Deterrence's Fixed Rules state that the ARMING (R) ADJACENTLY of previously Activated (C) Nuclear Units of all types IS ALWAYS NOT a COMPLETE TURN by the two eligible Arming Conventional Units (either the President Unit or the Envoy Unit).  This selection therefore ONLY ALLOWS the Players during either one or both rounds of Treaty negotiations to select WHETHER OR NOT the Arming of an eligible Nuclear Unit AT A DISTANCE by the Envoy Unit ONLY, since the President CANNOT Arm at a distance, should count as ONE COMPLETE TURN.</p>
              <p className="padding-bottom">The Default Setting for this is:  YES, meaning that any desired Envoy Move Elements must occur on either prior or subsequent Complete Turns, instead of on the Complete Turn when the Player CHOOSES TO ARM (R) any one of the eligible previously Activated (C) Nuclear Units AT A DISTANCE ONLY.  If the Player CHOOSES NOT to move the Envoy, that Player has NEVER AN OPPORTUNITY, during that Complete Turn, to move any of the other Unit(s) during that Complete Turn.  Deterrence's Fixed Rules of course EXPRESSLY PROHIBIT the movement of any other Unit(s) on the Game Board NOT INVOLVED in ANY ARMING OR HANDING OFF Move Element(s) within that specific Complete Turn of said arming or handing off.</p>
        <h3 className="padding-bottom padding-top section-color">Section Four:  Settings Affecting Conventional Unit Move Elements:</h3>
            <h4 className="text-center padding-bottom">The first setting:  Shall <em>en passant</em> (e.p) Infantry Unit captures (x) or destroys (z) Move Elements be legal?</h4>
                <p className="padding-bottom">For more information on the conditions in which this type of capture (x) or destroys (z) Infantry Unit Move Elements may occur, refer to Official Rules:  All Score Sheet Operator Codes: <em>En Passant Move Element Code, for more information.</em></p>
                <p className="padding-bottom"> The Players here have a YES or NO choice for this option under either one or both rounds of Treaty negotiations.  The Default Setting for this is:  YES.</p>
            <h4 className="text-center padding-bottom">The second setting:  Selection for type of Infantry Promotion:</h4>
                <p className="padding-bottom">This setting allows for Players to affect if and how a Player may "promote" an Infantry Unit landing on its last available square of movement.  This selected setting is in effect ON THE COMPLETE TURN WHEN an Infantry Unit from the Starting Player's forces reaches a square on the 8th rank OR when an Infantry Unit from the Responding Player's forces reaches a square on the 1st rank.  At that point, the Infantry Unit is removed from the Game Board and ONE of these selections applies.  Players may select from ONE of THREE AVAILABLE CHOICES below for this Variable Rule.  Players must take care to properly apply both Score Sheet Game Points and Cash Value Game Points to their respective totals as applicable.</p>
                <h5 className="text-center padding-bottom selection-color">The first selection:  NO PROMOTION ALLOWED. </h5>
                <p className="padding-bottom"> On this setting, the Player records +2.0 Score Sheet Game Points to that Player's Score Sheet Game Points Total WHILE DEDUCTING -1.0 Cash Value Game Points from that Player's Cash Value Game Points Total, since the Infantry Unit STILL GETS REMOVED from the Game Board.  On the rare cases where a Mobile Tactical Nuclear Unit and/or a Mobile SDI Defense Unit reach that promotion square with the Infantry Unit, the same rule applies here.  Two times that Unit's or Units' Cash Value Points get applied to that Player's Score Sheet Game Points Total ONLY 1X POINTS GET DEDUCTED from that Player's Cash Value Game Points Total.  Nothing remains on the square of "promotion" until a Player might use that square during a subsequent Complete Turn.  The correct Score Sheet Complete Turn entry syntax example here is: <em>d1=+2.0</em> OR <em>d1/MTN=+10.0</em> <em>OR d1/MTN/MSDI=+14.0</em> OR <em>d1/MSDI=+6.0</em>.  Here, the shorthand syntax omitting the Mobile Unit(s) is also legal, provided that the Points awarded to the right of the equals sign are in the correct amount.</p>
                <h5 className="text-center padding-bottom selection-color">The second selection:  PROMOTION ONLY TO PREVIOUSLY CAPTURED UNIT(S).</h5>
                <p className="padding-bottom">This setting gives Players the ability to promote an Infantry Unit TO ANY ONE per INFANTRY UNIT of the following Units: either the General, or the Lieutenant, or the Sergeant, or the Airdrop Unit with ONE KEY restriction.  Note that more than one Infantry Unit may be promoted, if available.  The condition causing this restricted promotion is as follows:  The Unit selected in the promotion move to REPLACE THE INFANTRY UNIT on the Game Board MUST HAVE BEEN PREVIOUSLY CAPTURED (x) at an earlier point in the current game.  Note that the above Unit(s) CANNOT be used in a Promotion Move Element when this setting is selected when the Unit was earlier destroyed (z) in a Nuclear Unit Firing Move Element (F).  As is the case of other Mobile Units described in the examples above reaching the promotion square, the Mobile SDI Defense Unit remains unchanged, and the Mobile Tactical Nuclear Unit ONLY PROMOTES to a Mobile Intermediate Nuclear Unit if the original Mobile Intermediate Nuclear Unit had BEEN CAPTURED (x) previously.  Again, a (z) outcome causes the rule in the first option above to be implemented during a Promotion Move Element with this setting selected.  Examples of this second setting follow here: <em>d1=G</em> OR <em>d1/MTN=G/MIN</em> OR <em>d1/MTN/MSDI=G/MIN/MSDI</em> OR the use of any of the first setting's examples above if Promotion is NOT POSSIBLE when the Unit(s) HAVE NOT BEEN previously captured.  A Mobile SDI Defense Unit reaching the promotion square retains its same Unit selected for protection from Nuclear Unit Firing Move Elements (either the new Conventional Unit OR the new Mobile Intermediate Nuclear Unit) and itself remains unchanged.  The newly promoted Mobile Intermediate Nuclear Unit retains its same level of readiness as when it was a Mobile Tactical Nuclear Unit.  It is important to note that the promotion move means that selecting the Points as an option as described in the first setting's examples IS NOT ALLOWED if promotion is legally authorized to occur.</p>
                <h5 className="text-center padding-bottom selection-color">The third selection:  PROMOTION TO ANY UNIT(S).</h5>
                <p>As in the game of chess, this setting gives Players the ability to promote an Infantry Unit TO ANY ONE per INFANTRY UNIT of the following Units: either the General, or the Lieutenant, or the Sergeant, or the Airdrop Unit.  The above changes to the position described also apply for this setting as well.  This setting is the DEFAULT SETTING within the Treaty Negotiations Chart for this Variable Rule.  Note that more than one Infantry Unit may be promoted, if available.  Note also that multiple copies of Unit(s) (beyond what started in the begiining of the game)also can be placed on the Game Board during Promotion when this setting IS SELECTED, even if one is already present on the Game Board (both the Conventional and/or the Nuclear Unit(s) reaching the Infantry Unit's final elibible square for movement).  As is the case of other Mobile Units described in the examples above reaching the promotion square, the Mobile SDI Defense Unit remains unchanged, and the Mobile Tactical Nuclear Unit ALWAYS PROMOTES to a Mobile Intermediate Nuclear Unit.  Examples of this third Default Setting follow here: <em>d1=G</em> OR <em>d1/MTN=G/MIN</em> OR <em>d1/MTN/MSDI=G/MIN/MSDI</em>.  A Mobile SDI Defense Unit reaching the promotion square retains its same Unit selected for protection from Nuclear Unit Firing Move Elements (either the new Conventional Unit OR the new Mobile Intermediate Nuclear Unit).  The newly promoted Mobile Intermediate Nuclear Unit retains its same level of readiness as when it was a Mobile Tactical Nuclear Unit.  It is important to note that the promotion move means that selecting the Points as an option as described in the first setting's examples IS NOT ALLOWED.</p>
            <h4 className="text-center padding-top padding-bottom">The third setting:  Allow Protecting the President Move Elements?</h4>
                <p className="padding-bottom">This setting allows the Players during either one or both rounds of Treaty negotiations to determine whether or not BOTH TYPES of Protect the President (both Long and Short) are legal.  The Default Setting within the Treaty Negotiations Chart is:  YES.  Refer to Official Rules: All Move Element Codes:  Protect the President (either -Long or -Short) for an in-depth explanantion for the conditions needing to be met to execute either one of these two Move Elements.</p>
            <h4 className="text-center padding-top padding-bottom">The fourth setting:  Allow Capture of Presidents Left in Check (+)?</h4>
                <p>This setting allows the Players during either one or both rounds of Treaty negotiations to determine whether or not inadvertently (or out of necessity in checkmate situations) leaving that attacked Player's President in check (+) for available capture(x) by the attacking Player on the subsequent Complete Turn is in fact legal.  Most chessplayers know this Variable Rule in Deterrence as the chess equivalent of "the speed chess rule" or the "blitz chess rule."  The Default Setting within the Treaty Negotiations Chart is:  NO, which means that any Player found to have left a President in check during that Complete Turn that President WAS FIRST PLACED INTO CHECK (threatened with opposing Conventional Unit capture) can be subject to that attacking Player's IMD-S declaration for the Illegal Move Declared - Successfully Complete Turn (see Official Rules: All Order Elements:  Illegal Move Declared - Successfully, for more information).</p>
                <p>If the YES selection is agreed to, then, an attacking Player HAS THE CHOICE to either capture (x) the President and end the game AS IF other ending-game Complete Turn(s) have occurred, OR NOT CAPTURE that President.  If that Player DOES CAPTURE that President, that Player receives the FIRST OUTCOME POINT for the POSITIONAL PORTION of the game.  Note here also that the CHECKMATE POINTS SETTING is NOT APPLIED (and also the President DOES NOT HAVE Cash Value upon capture (x)), but the game does still end, and the same procedure used after for ending the game, like other game-ending Complete Turns, still remains the same.</p>
            <h4 className="text-center padding-top padding-bottom">The fifth setting:  Total Number of Envoy Declarations (E=) Allowed: </h4>
                <p className="padding-bottom">The Players may choose during either one or both rounds of Treaty negotiations the number of allowable times throughout the course of the ENTIRE GAME, inclusive of the first and last COMPLETE TURNS for the Players, they will be allowed to make Declare Envoy (E=) Order Elements.  This Variable Rule allows either Player suffering the loss of either a captured (x) or destroyed (z) Envoy to THEN REPLACE that Envoy with a newly declared one, provided an available legally-authorized friendly Conventional Unit currently rests on the Game Board.  This setting is the one that MUST BE ENTERED as ONLY A POSITIVE INTEGER FROM ONE THROUGH SEVEN, inclusive of both integers, since there are only seven available Units at game's start which any one of those seven, can serve as an Envoy Unit.  Note that an Envoy can BE DECLARED at ANY TIME THROUGHOUT the game, regardless of the readiness level and/or presence of ANY NUCLEAR UNITS of both sides either being or not being on the Game Board at the time(s) of envoy declarations.  Use the (E) Unit Code to replace the selected Unit's original Unit Code at game's start to refer to Order and/or Move Elements made by that new Envoy Unit.  ONLY ONE ENVOY PER PLAYER AT A TIME CAN EXIST on the Game Board at any given point during the game.  provided that the Conventional Unit selected can LEGALLY BE an Envoy Unit.  Only the President Unit and ALL of the Infantry Units are EXCLUDED from being declared an envoy.  The Default Setting for this is: 1 TIME</p>   
        <h3 className="padding-bottom section-color">Section Five:  All Other Points Settings (those NOT in Section 2):</h3>
            <h4 className="text-center padding-top padding-bottom points-setting-color">The first Points Setting:  Illegal Move Declared - Successfully (IMD - S):</h4>
                <p>This setting allows Players to agree during either one or both rounds of Treaty negotiations to change the amount of Score Sheet Game Points applied during an Illegal Move Declared - Successfully Order Element which itself is that current COMPLETE TURN, IMMEDIATELY FOLLOWING the Element(s) or portions of Element(s) being questioned during the most RECENT PRECEDING Complete Turn.  The Official Rules for this type of Complete Turn can be found under Official Rules: All Order Element Codes:  Illegal Move Declared - Successfully, for more information.  The Default Setting for this is: +5.0 Points.  When it is determined that the challenge is VALID by either review of the Official Rule(s) relevant to the challenge(s) undertaken by that Player OR the Treaty Negotiations Chart Setting(s) relevant to the current challenge, the (S) is written to the RIGHT SIDE of the Separator Operator (-) in the (IMD- ) Order Element Code.  Then, that Player then applies that setting of Points to that Player's Score Sheet Game Points Total.  The Cash Value Game Points of either Player are each NOT AFFECTED, and then play resumes with the Player's challenged ENTIRE Complete Turn being COMPLETELY RETRACTED and that Player attempting another Complete Turn with play resuming as usual.  The Player recording this IMD-S, always a Complete Turn in and of itself, records a "strike" against the opposing Player, and "three strikes total" would then STRIKE OUT the opposing Player, resulting in BOTH OUTCOME POINTS BEING AWARDED AUTOMATICALLY to the Player issuing the strikeout, and the game ending immediately.</p>
            <h4 className="text-center padding-top padding-bottom points-setting-color">The second Points Setting:  Illegal Move Declared - Unsuccessfully (IMD - U):</h4>
                <p>This setting allows Players to agree during either one or both rounds of Treaty negotiations to change the amount of Score Sheet Game Points applied during an Illegal Move Declared - Unsuccessfully Order Element which itself is that current COMPLETE TURN, IMMEDIATELY FOLLOWING the Element(s) or portions of Element(s) being questioned during the most RECENT PRECEDING Complete Turn.  The Official Rules for this type of Complete Turn can be found under Official Rules: All Order Element Codes:  Illegal Move Declared - Unsuccessfully, for more information.  The Default Setting for this is: -5.0 Points.  When it is determined that the challenge is NOT VALID by either review of the Official Rule(s) relevant to the challenge(s) undertaken by that Player OR the Treaty Negotiations Chart Setting(s) relevant to the current challenge(s), the (U) is written to the RIGHT SIDE of the Separator Operator (-) in the (IMD- ) Order Element Code.  Then, that Player then applies that setting of Points to that Player's Score Sheet Game Points Total.  The Cash Value Game Points of either Player are each NOT AFFECTED, and then play resumes with the Player's challenged ENTIRE Complete Turn being COMPLETELY ALLOWED TO STAND AND REMAIN on the Game Board as is and that Player then attempting another Complete Turn with play resuming as usual.  The Player recording this IMD-U, always a Complete Turn in and of itself, records a "ball" against the opposing Player, and "four balls total" would then WALK the opposing Player, resulting in BOTH OUTCOME POINTS BEING AWARDED AUTOMATICALLY to the Player receiving the issued walk, and the game ending immediately.</p>
            <h4 className="text-center padding-top padding-bottom points-setting-color">The third Points Setting:  Checkmate (#):</h4>
                <p>This setting allows Players to determine during either one or both rounds of Treaty negotiations what the Points Setting applied to Complete Turns ending the game via checkmate (#) should be.  The Default Setting for this is:  +10.0 Points.  A game ends in checkmate immediately upon one Player, the attacking Player, causing the opposing Player, or defending Player, NOT TO BE ABLE TO AVOID the capture (x) of the defender's President on ANY AVAILABLE MOVE OR ORDER ELEMENT(S) legally able to be made to evade the threatened capturing Conventional Unit(s) on the attacking Player's subsequent Complete Turn.</p>
                <p>Threatened Firing (F) of Armed (R) Nuclear Units in RANGE of the opposing President (not protected by either type of SDI Defense Unit) under attack DOES NOT constitute check (+) and therefore, those Move Elements of that type CARRIED OUT are NOT THE SAME as checkmate (#).  Therefore, the Checkmate Setting is NOT APPLIED TO POINTS under those circumastances.</p>
            <h4 className="text-center padding-top padding-bottom points-setting-color">The fourth Points Setting: <em>Resigns:</em> <em>(resigns)</em></h4>
                <p>During either one or both rounds of Treaty negotiations, either Player may choose to "resign" by conceding believed inevitable defeat.  When one Player feels certain that either the current position on the Game Board offers NO HOPE of allowing for a draw or a win or the whole game (both Outcome Points in question) matches this believed state, that Player has the authority to Resign <em>(resigns)</em>, or give up, ONLY THE POSITIONAL PORTION, or the FIRST OUTCOME POINT of the game.  However, the Default Setting for doing this is -10.0 Points, the opposite of the Checkmate Setting described above.  Note here again the Checkmate (#) setting above DOES NOT get applied here, and the game DOES STILL end immediately, with end-of game procedures in effect needing to be carried out by both Players.</p>
            <h4 className="text-center padding-top padding-bottom points-setting-color">The fifth Points Setting:  The Envoy's (E) Extra Cash Value Added:</h4>
                <p className="padding-bottom">Since different types of Conventional Units OTHER THAN INFANTRY UNITS OR the two PRESIDENT UNITS, namely the General, or one of the Lieutenant Units, or one of the Sergeant Units, or one of the Airdrop Units can legally be declared as that Player's Envoy (E), the Unit selected INCREASES IN CASH VALUE based upon this Points Setting.  During either one or both rounds of Treaty negotiations, the Players may agree, but do not have to, to CHANGE this Points Setting up to and inclusive of the value of the positive real number 9.0, since that Cash Value is the highest per individual Unit (the General Unit) possible when the game starts.  The Default Setting for this is:  +1.0 Point.  Keep in mind that the selected Envoy Unit ALWAYS RETAINS that extra Cash Value throughout the game, until either being captured (x) or destroyed (z) in a Nuclear Unit Firing Move Element (F).  Players must remember this when applying Points as needed related to Envoy Unit Complete Turns.</p>
        <h3 className="padding-bottom section-color">Section Six:  Settings for Installing and Enforcing a Border in the Game:</h3>
            <h4 className="text-center padding-top padding-bottom">The first setting:  Shall a Border be installed in this game?</h4>
                <p>Deterrence, unlike chess, allows its Players the option of installing a Border within this Section of the Treaty Negotiations Chart during either one or both rounds of Treaty negotiations.  The Default Setting for this is:  NO BORDER.  On this first setting, the Players may choose either TO or NOT TO install a Border which will be in effect for the rest of the game, or until the second round of negotiations produces a Revised Treaty, possibly amending the original Border.  A Border described in either Treaty agreed to in either round of negotiations MAY NOT INCLUDE any one or more opposing Units of either Player in the other Player's territory.  Players may utilize a standard border drawing a horizontal "line" between ranks 4 and 5 of the Game Board.  Regardless if it is either the first or second round of negotiations, if the Starting Player is asking for a Treaty, the Treaty entry for the setting below ON BOTH SCORE SHEETS to describe this Border would be "a4/a5 - h4/h5."  If the Responding Player were asking for the Treaty, the entry would be "h5/h4 - a5/a4" ON BOTH SCORE SHEETS.</p>
                <p className="padding-top">The notation starts from the asking Player's LEFT, and proceeds to that asking Player's RIGHT, with the square in the asking Player's territory entered LEFT OF EACH PAIRS WITH OPERATOR (/) for each point-of-change in the Border and the answering Player's square TO THE RIGHT OF EACH PAIRS WITH OPERATOR (/) with each "pair" of squares listed representing a point or points where the Border changes (for custom Borders described more fully in the following section).  Each point-of-change is separated by the Separator Operator (-)</p>  
            <h4 className="text-center padding-top padding-bottom">The second setting:  Describe the Border at points-of-change:</h4>
                <p>The new Border selected by and agreed to by both Players in either one or both rounds of Treaty negotiations MUST BE ENTERED EXACTLY THE SAME WAY on each Player's Treaty Negotiations Chart, as outlined in the rules above for Setting One of THIS SECTION.  The Border chosen NEED NOT allow for each Player to retain 32 total squares of territory.  During negotiations, a Player might OFFER SQUARES in exchange for other concessions requested for a Treaty the offering Player wants.  However, all points-of-change have to be described in the manner outlined in the just-above section to legally install a Border.  An example of a custom Border during the Starting Player's asking for a Treaty in either round of negotiations could be:  <em>a3/a4 - d3/c4 - d4/c5 - f4/e5 - f5/e6 - h5/h6</em>.  This Border allows for three horizontal squares on each Player's LEFT side to be assigned differently as territory than the standard Border described in the above section.  If the Responding Player is asking for a Treaty in either round of negotiations, the notation would be changed and entered as the following: <em>h6/h5 - e6/f5 - e5/f4 - c5/d4 - c4/d3 - a4/a3</em>.</p>
            <h4 className="text-center padding-top padding-bottom">The third setting: Enforcement Type for Border Breach (BB) Move Elements:</h4>
                <p className="padding-bottom">This setting allows the Players to CHOOSE ONLY ONE METHOD from a list of THE FOLLOWING FIVE METHODS for how they have agreed to enforce the Border agreed to in either one or both rounds of Treaty negotiations.  Any time one Player has a Unit or Unit(s) ending movement within the other Player's territory, the Border Breach Move Element (BB) MUST BE RECORDED on that "breaking" Player's Score Sheet in the slot ONLY for the Complete Turn when the breach occurred.  Note that the number of Units breaching that Border during that entire specific COMPLETE TURN does not matter. When making a Border Breach, the "breaking" Player MUST RECORD the Border Breach Move Element Code (BB) to the ENDING RIGHT of that Complete Turn entry on the Score Sheet, using the Separator Operator (-) to separate the (BB) Element from the rest of the Complete Turn.  That "breaking" Player then applies Points in the amount of the agreed-to Points Setting described in the below setting section to that Player's Score Sheet Game Points Total.  ONLY ONCE per COMPLETE TURN does the "breaking" Player apply the agreed-to Points to that Player's own Score Sheet Game Points Total.  The Cash Value Game Points Total is not affected for both Players by JUST THE Border Breach Move Element (BB).</p>
                <p>If a Border is installed, the Players then MUST SELECT the Points Setting to be applied in the event a potentially "breaking" Player crosses the Border.  This Setting DOES NOT HAVE a Default Setting since the Default Setting for the first section herein is NO BORDER.  However, the Players MUST select an integer between and inclusive of -10 through +10 Points, just as in the case of some other Settings within the Treaty Negotiations Chart.  This integer CANNOT BE ZERO (0) BUT CAN INCLUDE EITHER -10 or +10.  Keep in mind that selecting a POSITIVE integer INSTEAD OF a NEGATIVE integer might incentivize the breach of the Border, creating more unstable and/or aggressive gameplay.  A higher NEGATIVE integer might create very conservative gameplay by DISINCENTIVIZING Border Breach Move Elements (BB).</p>
            <h4 className="text-center padding-top padding-bottom">The fourth setting:  Select Only One Enforcement Type (no Default Setting):</h4>
                <h5 className="text-center padding-bottom selection-color">The first selection:  ABSOLUTE.</h5>
                <p className="padding-bottom">This selection means that EVERY TIME ALTOGETHER FOR BOTH PLAYERS the Border is breached (BB), that Player applies the Points Setting EACH TIME throughout the duration of the game when the Border remains installed (if not replaced by NO BORDER in a First to Revised Treaty second round of Treaty negotiations).  This means that the Points Setting DOES NOT CHANGE AT ALL during following breaches of the Border, after the first one. </p>
                <h5 className="text-center padding-bottom selection-color">The second selection:  STAIRCASE OVERALL.</h5>
                <p className="padding-bottom">This selection means that EACH OVERALL TIME (regardless of which Player) the Border is breached, one integer value is deducted from the agreed-to Points Setting until the Points Setting for Border Breach Move Elements reaches ZERO, at which point the Border becomes a Border-in-name-only, but the Players ARE STILL REQUIRED to record the Border Breach Move Element (BB) on each of their Score Sheets.</p>  
                <p className="padding-bottom">FOR EXAMPLE: If a -5 Points Setting is agreed to, EVERY TIME REGARDLESS OF WHICH PLAYER DOES THE BREACH, the -5 goes down to -4 for the NEXT OVERALL BREACH of the Border, then down to -3, or in the case of a +5 Points Setting, goes down to +4, then +3, and so forth, until the integer reaches ZERO, meaning a Border-in-name-only (see above selection for reference).</p>
                <h5 className="text-center padding-bottom selection-color">The third selection:  STAIRCASE EACH PLAYER.</h5>
                <p className="padding-bottom">This selection means that FOR EACH PLAYER'S individual Border Breach Move Elements, does the Points Setting get reduced by one integer value FOR ONLY THAT PLAYER (for both positive and negative Points Settings selected in the above setting section -- see above) until THAT PLAYER'S setting value remaining total REACHES ZERO.  For example, if the Players agree to set the Points Setting in the above Setting to -5, if one Player commits the first two Border Breaches, FOR THAT PLAYER, the third such breach would be -3.  However, for the opposing Player's first breach of the Border (the third OVERALL in the game so far), THAT OPPOSING PLAYER still needs to apply the -5 Points Setting, and then -4, and so on.  Each Player INDEPENDENTLY APPLIES Border Breach Move Element (BB) Points Settings EACH TIME for ONLY THAT PLAYER'S OWN Border Breaches.</p>
                <h5 className="text-center padding-bottom selection-color">The fourth selection:  ONLY ONCE OVERALL.</h5>
                <p className="padding-bottom">This selection means that ONLY THE FIRST TIME OVERALL, does the player committing the FIRST OVERALL breach of the Border apply the agreed-to Points Setting in the above Setting.  Then ANY SUBSEQUENT Border Breach Move Elements still need to have the (BB) Code used on the Score Sheet, but WITHOUT ANY Points Setting applied, since the Points Setting IMMEDIATELY EQUALS ZERO for BOTH PLAYERS after that VERY FIRST Border Breach committed OVERALL.</p>
                <h5 className="text-center padding-bottom selection-color">The fifth selection:  ONCE EACH PLAYEROVERALL.</h5>
                <p className="padding-bottom">This selection means that ONLY THE FIRST TIME FOR EACH PLAYER, does that player committing that Player's FIRST BREACH of the Border apply the agreed-to Points Setting in the above Setting.  Then ANY SUBSEQUENT Border Breach Move Elements COMMITTED BY THAT PLAYER still need to have the (BB) Code used on the Score Sheet, but WITHOUT ANY Points Setting applied, since the Points Setting IMMEDIATELY EQUALS ZERO after that FIRST Border Breach committed JUST BY THAT PLAYER.  In other words, it takes ONE BORDER BREACH BY EACH PLAYER to get EACH PLAYER'S Points Setting to be ZERO, and to the state of a Border-in-name-only as described above. </p>
        <h3>Final Section:  Treaty Validation:</h3>
    </div>
  )
}

export default TreatyRules;