import React from "react";

const TreatyRules = () => {
  return (
    <div>TreatyRules
        <h2>Deterrence Official Rules:  Treaty Negotiations Chart</h2>
        <h3>In chess, both Players know that all rules always remain the same throughout the course of the game.  Because of this, the computer software suites that have been developed are now powerful enough to supply any human Player with the strongest move(s) in any given game at any given time.  Even the World Human Champions cannot defeat the best "virtual" opponent(s).  Therefore, players cannot be entirely sure, that when playing online or in-person, for that matter, that they in fact are playing the opponent(s) they think they are playing.  Cheating can be difficult to both eradicate and prevent, even within the setting of "over-the-board" or "in-person" chess tournaments, due to both the availability and capability of today's mobile connectivity devices.</h3>
        <p>The Deterrence Treaty Negotiations Chart addresses this first concern of chess by allowing Players to play the game with a custom set of Variable Rules and Points Settings each time, reflecting the way in which each Player prefers to play, and the results of the two total available rounds of Treaty Negotiations.  The Fixed Rules cannot be changed during the process of Treaty Negotiations (see Deterrence Official Rules:  Fixed Rules, for more information).  Each Player has only one opportunity to ask the opposing Player for Treaty Negotiations throughout the course of each game. Either or both Players can elect to forego asking for a Treaty.  Treaty Negotiations can occur at any point during the game, up to and inclusive of the Complete Turn prior to the Complete Turn that ends the game, when the position has been decided (win-lose-draw).  The Player answering a request for Treaty Negotiations can respond in one of the following three ways: ( ONE )refuse a Treaty outright ( the Treaty is not agreed to, and the Default Settings within the Treaty Negotiations Chart the game begins with or the settings in the existing Treaty from the first round of negotiations remain in effect ), ( TWO ) can participate in a negotiating session that results in the failure of both Players to agree to make the same changes to the Treaty ( the Treaty is not agreed to, and the current settings the game has, as explained above, remain in effect ), or, in the last case ( THREE ), an agreement is successfully reached, whereby all Variable Rules changes and Points Settings changes have been completely agreed to by both Players exactly, the Treaty takes effect at that time on the subsequent Complete Turn, and that Treaty now changes those Variable Rules and/or Points Settings that the Players have agreed to change during negotiations.  If the first round of negotiations results in an agreement, the Treaty taking effect is called the First Treaty. If the second round of negotiations also results in agreed-to changes after the First Treaty has been implemented, the second Treaty taking effect is called a Revised Treaty.  If the second round of negotiations DOES NOT end in an agreement, the First Treaty remains in effect, just as the Default Settings of the Treaty Negotiations Chart would have remained in effect had there not been a First Treaty agreed to in the first round of negotiations.  A second round of negotiations can also be used to return a First Treaty's selections back to the game's Default Settings in the Treaty Negotiations Chart.</p>
        <p>The other difficulty within the game of chess relates to the virtual certainty that a Player behind in material or behind in the positional layout will lose the game if the "leading" Player has a at least a minimal level of playing ability.  To address this concern, Deterrence has introduced the concept of Game Points.  The Treaty allows each player the opportunity to change Points Settings affecting the distribution of Score Sheet Game Points, depending on what occurs during the course of the game.  The Cash Value Game Points of each of the Conventional Units, and each Mobile Nuclear Unit, and each Mobile SDI Defense Unit cannot be changed during Treaty Negotiations.  These settings are in fact, Fixed Rules.</p>
    </div>
  )
}

export default TreatyRules;