import React from "react";

const ScoreRules = () => {
  return (
    <div>
        <h1>Deterrence Official Score Sheet v5.x.x:  Rules Section</h1>
        <h2>Official Rules for the Score Sheet</h2>
        <p>Each Player uses a Score Sheet for that Player to record events that occur throughout the course of the entire game.  Since certain Move Elements and Order Elements have time limitations associated with them, the Score Sheet determines what occurred at what point during the Game.  The Score Sheet relies upon Codes ( can be Unit, Order Element, and Move Element) that the Players use on each of their Score Sheets to describe what takes place during that Player's Complete Turn.  In chess, every move is itself only one move during that Player's turn, so the term "move" suffices.  However, in Deterrence, there can be multiple changes to the Game coming from that Player's Complete Turn, so the distinction has to be made between an Element and a Complete Turn.</p>
        <p>An Element describes one portion of a Complete Turn.  In the event that a Complete Turn contains two, or rarely three, Elements within that turn, all Elements listed on the Score Sheet must be separated by the Listing Operator (,).  Since Deterrence introduces new concepts related to both orders and movements given to the Units, some of which are not present in chess, there can be sometimes more than one Element within a Complete Turn.  A common example of this is when a Player wishes to move a Mobile Nuclear or Mobile SDI Defense Unit while also moving a Conventional Unit during that Complete Turn (see Official Rules:  All Score Sheet Move Element Codes and Order Element Codes, for more information).  Also, an Order Element can be executed, which does not affect the current position of the game, but does change the readiness or status of a given Unit.  A common example of this is when a Player selects a Conventional Unit to be the Envoy (the one Unit which can arm Nuclear Units at a distance) outside of a President being protected.  Within a Complete Turn, the order in which the Player lists the Elements within that Complete Turn can sometimes matter.  If rules pertaining to the potentially listed "out of order" elements cannot be met at that point in the position, the element(s) being challenged can make that whole Complete Turn need to be retracted (see Official Rules, Order Element Codes, Illegal Move Declarations, for more information).  A common example of this situation occurs when a Player attempts to move or arm a Nuclear Unit NOT IN RANGE of that Conventional Unit until either before or after that Unit moves during that Complete Turn. </p>
        <p>A Complete Turn contains all of the Elements contained within that Turn.  When the Complete Turn is entered on the Score Sheet beside that Player's number listing, and then the changes (if applicable) are made on the Game Board, it becomes then the opposing Player's turn.  In tournament play, only when the Player engages the time-control device as the final act of that turn, does it then become the opposing Player's turn.  In Deterrence, the "touch-move" rule is replaced with the "Score Sheet Complete Turn Entry Rule", regardless of when that Player chooses to make any applicable changes to Units' locations on the Game Board and/or Unit readiness or status.</p>
        <h2>Possible Ways to Assign the Two Outcome Points at the end of the game:</h2>
        <h3>In the game of chess, the players compete for only one Outcome Point, which refers to the outcome of the position.  However, in Deterrence, an additional second Outcome Point refers to the outcome of the Game Points portion of the game.  The Player with the greater total of Game Points, of course, wins the second Outcome Point at the conclusion of the game.  There are two types of Game Points.  The Score Sheet Game Points refer to "scored" points that change the Score at that point in the game.  The Cash Value Game Points reflect Units' values that have yet to be removed from the Game Board via capture/destroy Move Elements.  Each Player's Cash Value Game Points Total gets added to that Player's Score Sheet Game Points Total when the position of the game has been determined, at which point the game ends.</h3>
        <ol>
          <li>The Starting Player won the Game and both Outcome Points: 2.0 - 0.0</li>
          <li>The Starting Player won the Game and one of the two Outcome Points while sharing the other Outcome Point with the Responding Player: 1.5 - 0.5</li>
          <li>Both Players won one of each of the two total Outcome Points (drawn game): 1.0 - 1.0</li>
          <li>Both Players shared (or halved) each of both Outcome Points (drawn game): 1.0 - 1.0</li>
          <li>The Responding Player won the Game and one of the two Outcome Points while sharing the other with the Starting Player: 0.5 - 1.5</li>
          <li>The Responding Player won the Game and both Outcome Points: 0.0 - 2.0</li>
        </ol>
        <h2>Score Sheet Validation at the end of the game:</h2>
        <p>When the position of the game has been decided (a drawn position or one of the two Players winning the position and the other Player losing), the game ends.  Each Player's first task is then to tabulate all of only that Player's Cash Value Points of each of that Player's remaining Units on the Game Board (some Units do not have a Cash Value).  Then, that Player takes that Cash Value Game Points Total and adds that total to that Player's current Score Sheet Game Points Total.  That new total is then compared with the opposing Player's Game Points Total reached in the same manner.  The Player with the mathematically greater number of Game Points (both Score Sheet and Cash Value added together) wins the second Outcome Point, and the opposing Player loses the second Outcome Point.  If both Players have a mathematically equal number of Game Points, that second Outcome Point is shared equally (halved, or 0.5 - 0.5).  Keep in mind that Treaty selections can cause either of the two Outcome Points to be automatically awarded to the Player based upon the positional or the Game Points Outcomes (see Official Rules, Treaty: Section One, for more information).  The Default Settings within the Treaty Negotiations Chart allow only for the two Outcome Points to be distributed according to the procedures contained in this section (each of the two being distributed separately, not automatically resulting from how one of the two is distributed).  These Variable Rules outlined in the Treaty Negotiations Chart allow for a simplified end-of game experience the Players may wish to agree to during Treaty negotiations.</p>
        <p>The Players next have the responsibility of reviewing their own Score Sheets to determine that applied Points during their Complete Turns are all indeed both accurate and legal.  If a Player correctly determines that the opposing Player has inadvertently in error not applied Points to that Player's Score Sheet Game Points total correctly, the challenging Player can "claim" those Points if that Player wishes to do so, although there is no obligation to do this, and doing so might not always be to that Player's advantage, since that Player might then face the same review initiated by the opposing Player, and vice versa (there are no specific guidelines on this portion of the game, however, both Players must be in agreement about the Game Points Totals of each prior to the selection of the Game Outcome on the Score Sheet.  Once agreement is reached, only one of the Game Outcome options in the above list is circled on the Score Sheet, and each Player must sign (or electronically sign) the Score Sheet to indicate the resolution of the Game.  In a tourament setting, the overall results (the places the Players finish in) depend on how many total Outcome Points each Player has won throughout the course of the tournament, just as in a chess tournament.</p>
        <p>After the assignment of the two Outcome Points has been completed AND the Score Sheets BOTH are signed and dated, the result of the game becomes official, and subscribers' win-loss-draw records are subsequently updated.  Subscribers to the website have the opportunity to authorize other Subscribers at that tier level to review their electronically-stored Score Sheets and the companion Treaties (if applicable) of not just game between them but also games involving other Players.  There might be various promotions or events that use Player records to determine eligibility, rewards, merchandise discounts, waiver or reduction of tournament entry fees, or other possibilities.</p>
    </div>
  )
}

export default ScoreRules;