
import React, { useState } from "react";
import './ScoreRules.css';
import Popup from "../Popup/Popup.js";
import ScoreSheet from "../ScoreSheetv5.0.1/ScoreSheet.js";

const ScoreRules = () => {
  const [ getSheet, setGetSheet ] = useState(false);

  return (
    <div className="score-rules-wrapper">
        <header className="header-wrapper">
          <h1>Deterrence Official Score Sheet v5.0.1:  Rules Section</h1>
        </header>
        <h2 className="text-center section-headings padding-bottom">Official Rules for the Score Sheet</h2>
        <p className="padding-top padding-bottom">Each Player uses a Score Sheet for that Player to record events that occur throughout the course of the entire game.  Since certain Move Elements and Order Elements have time limitations associated with them, the Score Sheet determines what occurred at what point during the Game.  The Score Sheet relies upon Codes ( can be either Unit, or Order Element, or Move Element, or any combination of these) that the Players use on each of their Score Sheets to describe what takes place during that Player's Complete Turn.  In chess, every "move" is itself only one "move" during that Player's turn, so the term "move" suffices.  However, in Deterrence, there can be multiple changes to the Game coming from that Player's Complete Turn, so the distinction has to be made between an Element (either an Order Element OR a Move Element OR both) and a Complete Turn, which is the "container" that "holds" either the ONE, TWO, or in a rare case, THREE TOTAL Elements.</p>
        <p className="padding-bottom">It is important to note here that how a Player LISTS those Complete Turns containing MORE THAN ONE Element DOES INDEED affect the legality of that Player's Complete Turn on that Player's Score Sheet.  For example, it would not MAKE ANY SENSE to list a Hand Off Move Element as THE FIRST Element of a Complete Turn IF the receiving Conventional Unit were NOT IN RANGE of the sending Conventional Unit UNTIL AFTER the sending Unit MOVES FIRST.  When more than one Element occurs in a Complete Turn, that Player uses the Listing Operator (,) to SEPARATE one Element from another.  Refer to Official Rules:  All Operator Codes:  Listing Operator, for more information.  These types of errors are called Complete Turn "out-of-order" Element Listing Errors, and the opposing Player MAY DECLARE such Complete Turns AS ILLEGAL, even if each of the listed ELEMENTS could have been legal on a STAND-ALONE BASIS (as each one being its own Complete Turn, for example).  Refer to Official Rules:  All Order Element Codes:  Illegal Element Declared - (both Successfully and Unsuccessfully) for more information.</p>
        <p className="padding-bottom">As described above, an Element describes one portion of a Complete Turn.  In the event that a Complete Turn contains two, or rarely three, Elements within that turn, all Elements listed on the Score Sheet must be separated by the Listing Operator (,).  Since Deterrence introduces new concepts related to both orders and movements given to the Units, some of which are not present in chess, there can be sometimes more than one Element within a Complete Turn.  A common example of this is when a Player wishes to move a Mobile Nuclear Unit (either the (MTN) or (MIN) Code) or Mobile SDI Defense Unit (MSDI) while also moving a Conventional Unit during that Complete Turn (see Official Rules:  All Score Sheet Move Element Codes and Order Element Codes, for more information on the relevant Code(s) being studied).  Also, an Order Element can be executed, which does not affect the current position of the game, but does change the readiness or status of a given Unit.  This SOLE DISTINCTION separates the definition of an Order Element FROM a Move Element, which DOES INDEED make visible revisions (on one or both sides) to the position on the Game Board.  A common example of this is when a Player selects a Conventional Unit to be the Envoy (E=) (the one Unit which can arm Nuclear Units at a distance) outside of a President being protected (either the (O-O) Code for Short, or chess's "Kingside" OR the (O-O-O) Code for Long, or chess's "Queenside," we know from chess scoresheets).</p>
        <p className="padding-bottom">A Complete Turn contains all of the Elements "contained" within that Turn.  When the Complete Turn is entered on the Score Sheet beside that Player's number listing, and then the changes (if applicable) are made on the Game Board, it becomes then the opposing Player's Complete Turn (unless the game is being played within a tournament setting, at which time the Complete Turn does NOT BECOME FINAL until AFTER that Player engages the time-control device, regardless of change(s) made to the position on the Game Board, restarting the opposing Player's time).  This Fixed Rule (one that CANNOT BE CHANGED during either one or both rounds of Treaty negotiations) replaces the common "touch-move" rule chessplayers know.  Here, in the context of Deterrence, it is known as the "Complete Turn Score Sheet Entry Rule."  It is ALSO IMPORTANT to note that the Complete Turn IS NOT FINAL until the relevant changes to the positon on the Game Board have been physically made.  It is the Player's choice on which of those two items on the "Complete Turn To-Do List" gets done first, but BOTH MUST BE DONE ON THAT COMPLETE TURN before some part of that Complete Turn CAN BE DECLARED AS ILLEGAL (see above for a quick reference).  In tournament play, only when the Player engages the time-control device as the always then final act of that Complete Turn, does it then become the opposing Player's Complete Turn.  In Deterrence, the "touch-move" rule is replaced with the "Score Sheet Complete Turn Entry Rule", regardless of when that Player chooses to make any applicable changes to Units' locations on the Game Board and/or Unit readiness or status, which often times "cannot be seen" without having the accurate Score Sheet as a point of reference.</p>
        <h2 className=" text-center section-headings padding-bottom">Possible Ways to Assign the Two Outcome Points at the end of the game:</h2>
        <h3 className="heading-paragraphs padding-bottom">In the game of chess, the players compete for only one Outcome Point, which refers to the outcome of the position, which itself IS the WHOLE GAME.  However, in Deterrence, an additional second Outcome Point refers to the outcome of the new POINTS PORTION of the game.  The First OUTCOME POINT refers to the POSITIONAL PORTION of that game.  The Player with the greater total of Game Points, of course, wins the second Outcome Point at the conclusion of the game.  There are two types of Game Points.  The Score Sheet Game Points refer to "scored" points that change the Score at that point in the game.  The Cash Value Game Points reflect Units' values that have yet to be removed from the Game Board via Capture (x) or Destroy (z) Move Elements.  Each Player's Cash Value Game Points Total gets added to that Player's Score Sheet Game Points Total when the position of the game has been determined, at which point the game ends.  Refer also to Official Rules:  All General Game Rules, for a complete listing of how these two TOTAL OUTCOME POINTS might be distributed at the conclusion of a game (when the POSITIONAL PORTION of the game has been decided).</h3>
        <h2 className="section-headings padding-top padding-bottom">Applying Points on the Score Sheet during the game:</h2>
          <p className="padding-top padding-bottom">Your new Deterrence Official Score Sheet comes with a built-in feature that allows for EACH PLAYER to "Apply Points" (when applicable only) during the course of EACH ONE of their individual Complete Turns.  The column to the RIGHT of EACH PLAYER'S Complete Turn listing area contains a box for the POINTS APPLIED to be listed.  In some cases, the POSITIVE OR NEGATIVE sign denoting the mathematical value of each Points Setting MUST BE NOTED TO THE LEFT of the number reflecting the TOTAL VALUE of all applicable Points Settings relevant to that COMPLETE TURN.  Note here that ONLY THE NUMBER REPRESENTING THE TOTAL VALUE occurring on that Complete Turn, is ENTERED INTO THAT BOX to THE RIGHT OF that Complete Turn Score Sheet entry.  Sometimes, Players will use "shorthand syntax" to omit additional Codes from the Score Sheet during each Complete Turn.  This is NOT THE BEST PRACTICE, however, but IT IS STILL LEGAL, provided that the Points Setting entry for that Complete Turn DOES INDEED reflect the accurate amount of Points needing to be applied for that Complete Turn.  Then, the Player completing that turn CHANGES THE APPLICABLE Total(s) FOR EACH of either one or both of the Score Sheet Game Points Total and/or the Cash Value Game Points total FOR JUST THAT PLAYER.  Each Player, of course, IS OBLIGATED to "score" that Player's own Score Sheet, just as in a tournament chess game.</p>

        <span className="app-wrapper">
              <button id="ShowScoreSheet" className="score-sheet-btn" onClick={() => setGetSheet(true)}>See your new Score Sheet!</button>
              <Popup trigger={ getSheet } setTrigger={ setGetSheet }>
                <ScoreSheet />
              </Popup>
        </span>
        
        <h2 className="section-headings padding-bottom">Score Sheet Validation at the end of the game:</h2>
        <p className="padding-bottom">When the position of the game has been decided (a drawn position or one of the two Players winning the position and the other Player losing), the game ends.  Each Player's first task is then to tabulate all of only that Player's Cash Value Points of each of that Player's remaining Units on the Game Board (some Units do not have a Cash Value).  Then, that Player takes that Cash Value Game Points Total and adds that total to that Player's current Score Sheet Game Points Total.  That new total is then compared with the opposing Player's Game Points Total reached in the same manner.  The Player with the mathematically greater number of Game Points (both Score Sheet and Cash Value added together) wins the second Outcome Point, and the opposing Player loses the second Outcome Point.  If both Players have a mathematically equal number of Game Points, that second Outcome Point is shared equally (halved, or 0.5 - 0.5).  Keep in mind that Treaty selections can cause either of the two Outcome Points to be automatically awarded to the Player based upon the positional or the Game Points Outcomes (see Official Rules, Treaty: Section One, for more information).  The Default Settings within the Treaty Negotiations Chart allow only for the two Outcome Points to be distributed according to the procedures contained in this section (each of the two being distributed separately, not automatically resulting from how one of the two is distributed).  These Variable Rules outlined in the Treaty Negotiations Chart allow for a simplified end-of game experience the Players may wish to agree to during Treaty negotiations.</p>
        <p className="padding-bottom">The Players next have the responsibility of reviewing their own Score Sheets to determine that applied Points during their Complete Turns are all indeed both accurate and legal.  If a Player correctly determines that the opposing Player has inadvertently in error not applied Points to that Player's Score Sheet Game Points total correctly, the challenging Player can "claim" those Points if that Player wishes to do so, although there is no obligation to do this, and doing so might not always be to that Player's advantage, since that Player might then face the same review initiated by the opposing Player, and vice versa (there are no specific guidelines on this portion of the game, however, both Players must be in agreement about the Game Points Totals of each prior to the selection of the Game Outcome on the Score Sheet.  Once agreement is reached, only one of the Game Outcome options in the above list is circled on the Score Sheet, and each Player must sign (or electronically sign) the Score Sheet to indicate the resolution of the Game.  In a tourament setting, the overall results (the places the Players finish in) depend on how many total Outcome Points each Player has won throughout the course of the tournament, just as in a chess tournament.</p>
        <p className="padding-bottom">After the assignment of the two Outcome Points has been completed AND the Score Sheets BOTH are signed and dated, the result of the game becomes official, and subscribers' win-loss-draw records are subsequently updated.  Subscribers to the website have the opportunity to authorize other Subscribers at that tier level to review their electronically-stored Score Sheets and the companion Treaties (if applicable) of not just game between them but also games involving other Players.  There might be various promotions or events that use Player records to determine eligibility, rewards, merchandise discounts, waiver or reduction of tournament entry fees, or other possibilities.</p>
    </div>
  )
}

export default ScoreRules;